'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),zlib=require('zlib'),{promisify}=require('util');
const gunzip=promisify(zlib.gunzip);
const PORT=Number(process.env.PORT||3000),DEPT=process.env.DVF_DEPT||'08';
const YEARS=(process.env.DVF_YEARS||'2025,2024,2023,2022').split(',').map(Number).filter(Boolean);
const RADII=[.3,.75,1.5,3,5],MAX_MONTHS=24;
const RECENCY=[[3,1],[6,.95],[12,.85],[18,.65],[24,.4]];
const TYPES={
 house:{label:'Maison',area:'living',match:r=>norm(r.type_local)==='maison'},
 apartment:{label:'Appartement',area:'living',match:r=>norm(r.type_local)==='appartement'},
 land:{label:'Terrain à bâtir',area:'land',match:r=>/terrain\s+a\s+batir|terrain\s+constructible/.test(norm(r.nature_culture))},
 agricultural_land:{label:'Terrain agricole',area:'land',match:r=>/terre|pres|prairie|verger|vigne|bois|foret|taillis|lande|etang/.test(norm(r.nature_culture))&&!/terrain\s+a\s+batir/.test(norm(r.nature_culture))},
 commercial:{label:'Local commercial',area:'living',match:r=>commercial(r.type_local)},
 industrial:{label:'Local industriel / entrepôt',area:'living',match:r=>commercial(r.type_local)},
 garage:{label:'Garage / dépendance',area:'living',match:r=>norm(r.type_local)==='dependance'},
 parking:{label:'Parking',area:'living',match:r=>norm(r.type_local)==='dependance'},
 building:{label:'Immeuble',area:'living',match:()=>false},
 other:{label:'Autre bien',area:'living',match:()=>false}
};
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function n(v){const x=Number(String(v??'').replace(',','.').replace(/\s/g,''));return Number.isFinite(x)?x:0}
function date(v){const d=new Date(String(v||'').slice(0,10));return Number.isNaN(d.getTime())?null:d}
function ageMonths(d){return Math.max(0,(Date.now()-d.getTime())/2629800000)}
function dist(a,b,c,d){const p=Math.PI/180,x=.5-Math.cos((c-a)*p)/2+Math.cos(a*p)*Math.cos(b*p)*(1-Math.cos((d-b)*p))/2;return 12742*Math.asin(Math.sqrt(Math.max(0,x)))}
function rw(m){for(const [max,w] of RECENCY)if(m<=max)return w;return 0}
function median(a){const x=[...a].sort((a,b)=>a-b);if(!x.length)return 0;const i=(x.length-1)/2;return x[Math.floor(i)]===x[Math.ceil(i)]?x[Math.floor(i)]:(x[Math.floor(i)]+x[Math.ceil(i)])/2}
function percentile(a,p){const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return 0;const i=(x.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?x[l]:x[l]+(x[h]-x[l])*(i-l)}
function wmedian(rows){const x=rows.filter(r=>r.value>0&&r.weight>0).sort((a,b)=>a.value-b.value);if(!x.length)return 0;const t=x.reduce((s,r)=>s+r.weight,0);let a=0;for(const r of x){a+=r.weight;if(a>=t/2)return r.value}return x.at(-1).value}
function csvLine(s){const o=[];let c='',q=false;for(let i=0;i<s.length;i++){const z=s[i];if(z==='"'){if(q&&s[i+1]==='"'){c+='"';i++}else q=!q}else if(z===','&&!q){o.push(c);c=''}else c+=z}o.push(c);return o}
function csv(s){const l=s.split(/\r?\n/).filter(Boolean),h=csvLine(l[0]||'');return l.slice(1).map(z=>{const c=csvLine(z),r={};h.forEach((k,i)=>r[k]=c[i]??'');return r})}
function row(r){return{id:r.id_mutation,date:r.date_mutation,nature:r.nature_mutation,price:n(r.valeur_fonciere),streetNumber:r.adresse_numero,streetName:r.adresse_nom_voie,postal:r.code_postal,city:r.nom_commune,parcel:r.id_parcelle,type_local:r.type_local,nature_culture:r.nature_culture,livingArea:n(r.surface_reelle_bati),rooms:n(r.nombre_pieces_principales),landArea:n(r.surface_terrain),lat:n(r.latitude),lon:n(r.longitude)}}
function commercial(v){const s=norm(v);return s.includes('commercial')||s.includes('industriel')}
function consolidate(rows,cfg){const m=new Map();for(const r of rows)if(norm(r.nature)==='vente'&&cfg.match(r)&&r.id&&r.price&&r.date){const k=[r.id,r.type_local,r.streetNumber,norm(r.streetName),r.postal,r.parcel].join('|');if(!m.has(k))m.set(k,[]);m.get(k).push(r)}const out=[];for(const a of m.values()){if(a.length!==1)continue;const r=a[0],area=cfg.area==='land'?r.landArea:r.livingArea;if(area>0&&r.lat&&r.lon)out.push({...r,area,sqmPrice:r.price/area})}return out}
async function fetchYear(y){if(process.env.MOCK_DVF_MODE==='true')return mockRows(String(y));const u=`https://files.data.gouv.fr/geo-dvf/latest/csv/${y}/departements/${DEPT}.csv.gz`,r=await fetch(u);if(!r.ok)throw Error(`DVF ${y}: HTTP ${r.status}`);return csv((await gunzip(Buffer.from(await r.arrayBuffer()))).toString('utf8')).map(row)}
async function loadDvf(){return (await Promise.all(YEARS.map(y=>fetchYear(y).catch(()=>[])))).flat()}
async function geocode(address){if(process.env.MOCK_DVF_MODE==='true')return{lat:49.77,lon:4.72,label:address};const u=new URL('https://data.geopf.fr/geocodage/search');u.searchParams.set('q',address);u.searchParams.set('limit','1');const r=await fetch(u);if(!r.ok)throw Error(`Géocodage: HTTP ${r.status}`);const d=await r.json(),f=d.features?.[0];if(!f?.geometry?.coordinates)throw Error('Adresse introuvable. Vérifiez l’adresse saisie.');return{lat:f.geometry.coordinates[1],lon:f.geometry.coordinates[0],label:f.properties?.label||address}}
function score(r,t,rad){const type=25,d=20*Math.max(0,1-r.distance/rad),s=20*Math.max(0,1-Math.abs(r.area-t.area)/Math.max(1,t.area)),p=t.rooms&&r.rooms?10*Math.max(0,1-Math.abs(t.rooms-r.rooms)/5):5,l=t.landArea&&r.landArea?10*Math.max(0,1-Math.abs(t.landArea-r.landArea)/Math.max(1,t.landArea)):5,rec=15*rw(r.age);return type+d+s+p+l+rec}
function weight(r,t){const sr=Math.min(r.area,t.area)/Math.max(r.area,t.area);return rw(r.age)*Math.exp(-r.distance/.75)*Math.pow(sr,1.5)*(t.rooms&&r.rooms?Math.max(.35,1-Math.abs(t.rooms-r.rooms)*.12):.7)*(t.landArea&&r.landArea?Math.max(.35,Math.min(1,Math.min(t.landArea,r.landArea)/Math.max(t.landArea,r.landArea))):.8)*(.5+r.score/200)}
function select(rows,t,cfg){const base=consolidate(rows,cfg).map(r=>({...r,distance:dist(t.lat,t.lon,r.lat,r.lon),age:ageMonths(date(r.date))})).filter(r=>r.age<=MAX_MONTHS&&r.distance<=5&&r.sqmPrice>0),sel=[];for(const rad of RADII){for(const r of base.filter(x=>x.distance<=rad&&!sel.includes(x)).sort((a,b)=>score(b,t,rad)-score(a,t,rad))){r.score=score(r,t,rad);sel.push(r);if(sel.length>=20)break}if(sel.length>=6)break}const ps=sel.map(r=>r.sqmPrice),q1=percentile(ps,.25),q3=percentile(ps,.75),iqr=q3-q1,keep=iqr?sel.filter(r=>r.sqmPrice>=q1-1.5*iqr&&r.sqmPrice<=q3+1.5*iqr):sel;keep.forEach(r=>r.weight=weight(r,t));return keep.sort((a,b)=>b.weight-a.weight).slice(0,15)}
function confidence(c,t){if(!c.length)return 0;const avgD=c.reduce((s,r)=>s+r.distance,0)/c.length,avgA=c.reduce((s,r)=>s+r.age,0)/c.length,med=median(c.map(r=>r.sqmPrice)),mad=median(c.map(r=>Math.abs(r.sqmPrice-med))),surface=c.reduce((s,r)=>s+Math.max(0,1-Math.abs(r.area-t.area)/Math.max(1,t.area)),0)/c.length;return Math.max(0,Math.min(100,Math.round(Math.min(35,c.length*5)+Math.max(0,25-avgD*7)+Math.max(0,20-avgA*.7)+Math.max(0,20-mad/Math.max(1,med)*100)+surface*10)))}
function analyze(rows,input,geo){const cfg=TYPES[input.realtyType];if(!cfg)throw Error('Type de bien invalide.');if(['building','other'].includes(input.realtyType))return{manual:true,message:'Ce type n’est pas directement identifiable de façon fiable dans DVF V1. Une méthode dédiée est nécessaire pour éviter d’inventer un prix.'};const area=cfg.area==='land'?input.landArea:input.livingArea,t={...geo,area,rooms:input.rooms||0,landArea:input.landArea||0},c=select(rows,t,cfg);if(!c.length)return{manual:true,message:`Pas assez de ventes DVF exploitables pour ${cfg.label} dans les 24 derniers mois et 5 km.`};const sqm=wmedian(c.map(r=>({value:r.sqmPrice,weight:r.weight}))),estimate=Math.round(sqm*area/1000)*1000,local=median(c.map(r=>r.sqmPrice)),conf=confidence(c,t),avgD=c.reduce((s,r)=>s+r.distance,0)/c.length,avgA=c.reduce((s,r)=>s+r.age,0)/c.length;return{estimate,low:Math.max(0,estimate-20000),high:estimate+20000,rangeEur:20000,confidence:conf,confidenceLevel:conf>=80?'Élevée':conf>=60?'Bonne':conf>=40?'Moyenne':'Faible',method:'Médiane pondérée des ventes DVF comparables. Le prix propriétaire n’entre jamais dans le calcul.',statistics:{weightedMetric:sqm,localMedian:local,avgDistanceKm:avgD,avgAgeMonths:avgA,trendAnnualPct:null,adjustmentPct:0,metricLabel:'€/m²'},selection:{retained:c.length,directComparables:c.filter(r=>r.distance<=.75).length,radiusKm:Math.max(...c.map(r=>r.distance)),filter:'24 mois · type identique · IQR 1,5'},sources:[{name:'Ventes DVF comparables',value:estimate,weight:100,reason:`${c.length} ventes réelles retenues après filtrage.`},{name:'Médiane locale de contrôle',value:Math.round(local*area),weight:0,reason:'Contrôle de cohérence uniquement, jamais ajoutée au prix.'}],comparables:{data:c.map(r=>({date:r.date,streetName:r.streetName,streetNumber:r.streetNumber,livingArea:r.area,price:r.price,sqmPrice:r.sqmPrice,distanceKm:r.distance,score:Math.round(r.score),ageMonths:Math.round(r.age)}))},data:{source:'DVF+ géolocalisées — données ouvertes',millime:YEARS.join(', ')}}}
function validate(p){if(!p||!String(p.address||'').trim())throw Error('L’adresse du bien est obligatoire.');if(!TYPES[p.realtyType])throw Error('Type de bien invalide.');const area=['land','agricultural_land'].includes(p.realtyType)?n(p.landArea):n(p.livingArea);if(area<=0)throw Error('La surface du bien est obligatoire.');return{...p,livingArea:n(p.livingArea),landArea:n(p.landArea),rooms:n(p.rooms)}}
function send(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))}
function startServer(port=PORT){return http.createServer((req,res)=>{if(req.method==='GET'&&(req.url==='/'||req.url==='/index.html')){try{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(fs.readFileSync(path.join(__dirname,'public','index.html')))}catch(e){send(res,500,{error:'Interface introuvable.'})}return}if(req.method==='POST'&&req.url==='/api/analyze'){let b='';req.on('data',c=>{b+=c;if(b.length>65536)req.destroy()});req.on('end',async()=>{try{const input=validate(JSON.parse(b||'{}')),geo=await geocode(input.address),rows=await loadDvf();send(res,200,analyze(rows,input,geo))}catch(e){send(res,400,{error:e.message||'Erreur inconnue.'})}});return}send(res,404,{error:'Route introuvable.'})}).listen(port,()=>console.log(`JML Estimateur V1 sur http://localhost:${port}`))}
function mockRows(prefix=''){return[
['72','145000','2026-08-20','49.7705','4.7205','4','300','1'],['75','152000','2026-07-10','49.7710','4.7210','4','280','2'],['68','132000','2026-05-10','49.7720','4.7220','3','250','3'],['80','160000','2025-12-10','49.7730','4.7230','4','320','4'],['74','148000','2025-10-10','49.7740','4.7240','4','290','5']
].map(x=>row({id_mutation:prefix+'-m'+x[7],date_mutation:x[2],nature_mutation:'Vente',valeur_fonciere:x[1],adresse_numero:x[7],adresse_nom_voie:'Rue Test',code_postal:'08000',nom_commune:'Charleville-Mézières',id_parcelle:prefix+'-p'+x[7],type_local:'Maison',surface_reelle_bati:x[0],nombre_pieces_principales:x[5],surface_terrain:x[6],latitude:x[3],longitude:x[4]}))}
if(require.main===module)startServer();
module.exports={startServer,median,percentile,wmedian,rw,consolidate,analyze,mockRows,TYPES,geocode,loadDvf};